version: "3"

services:
  labs-report:
    container_name: labs-report
    build:
      context: ../..
      dockerfile: ./Dockerfile.builder
    image: labs-report:latest
    #volumes:
    #  - .:/usr/src/app
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
    command: npm run start:prod
