SELECT SE.NAME AS "Seller", CEIL(AVG(sysdate + (TC.START_CHANNEL_DATE - TS.START_CHANNEL_DATE)*24*60*60 - sysdate)) AS "Média resposta (segundos)" 
FROM (SELECT T.ID, T.TENANT_ID, T.TYPE, T.STATUS FROM CORE_PRD.TICKET T WHERE T.TYPE = 'PRE_ORDER' AND T.STATUS='CLOSED' AND T.CHANNEL_DATE   >= (TRUNC(SYSDATE) - 30) ORDER BY T.ID)  T
INNER JOIN (SELECT TS.ID, TS.TICKET_ID, TS.SELLER, TS.INDEX_, TS.START_CHANNEL_DATE  FROM CORE_PRD.TICKET_MESSAGE TS ORDER BY TS.TICKET_ID, TS.INDEX_) TS ON TS.TICKET_ID = T.ID AND TS.SELLER = 0 
INNER JOIN CORE_PRD.TICKET_MESSAGE TC ON TC.TICKET_ID = T.ID AND TC.SELLER = 1 AND TC.INDEX_ = TS.INDEX_ + 1 INNER JOIN CHRONUS.SELLER SE ON SE.TENANT_ID = T.TENANT_ID AND SE.STATUS = 'ACTIVE' 
WHERE TS.START_CHANNEL_DATE IS NOT NULL AND TC.START_CHANNEL_DATE IS NOT NULL 
AND TS.START_CHANNEL_DATE >= (TRUNC(SYSDATE) - 1) GROUP BY SE.NAME ORDER BY SE.NAME